add list command, by tgckpg@gmail.com,roootik@gmail.com https://github.com/tgckpg/bash-onedrive-upload.git https://github.com/rootik/bash-onedrive-upload.git

diff --git a/onedriveb-base b/onedriveb-base
--- a/onedriveb-base
+++ b/onedriveb-base
@@ -74,6 +74,19 @@ function curl_find_subfolder() {
 		"${url}" | "${json_parser}"
 }
 
+# $1=item path
+function curl_list_items() {
+	local item_path=$(urlencode "$1")
+	local url="${api_uri}/drive/root:/$item_path?expand=children(select=lastModifiedDateTime,size,name,folder,file)"
+
+	curl \
+		${curl_opts} \
+		--get \
+		--header "Authorization: Bearer ${api_access_token}" \
+		--header "Accept: application/json; odata.metadata=none" \
+		"${url}" | "${json_parser}"
+}
+
 # $1=parent_folder_id
 # $2=new_folder_name
 function curl_create_folder() {
@@ -324,6 +337,63 @@ function onedrive_create_folder() {
 	fi
 
 	echo "${api_parsed_json_result}" | grep -E "^id=" | ${get_json_value}
+}
+
+# $1=folder name
+function onedrive_list_items() {
+	local api_access_token
+	local total_folder_items=0
+	local item_name
+	local item_timestamp
+	local item_size
+	local item_type
+	local total_files=0
+	local total_file_size=0
+	
+	api_access_token=$(onedrive_acquire_access_token ${api_resource_id})
+	exit_on_error
+
+	local api_parsed_json_result=$(curl_list_items "$1")
+
+	if [[ -n $(echo "${api_parsed_json_result}" | grep -E "^error") ]]; then
+	    echo "${api_parsed_json_result}"
+	    return 1;
+	fi	
+		    
+	if [[ -n $(echo "${api_parsed_json_result}" | grep -E "^folder") ]]; then
+	    [[ ! $1 || $1 == / ]] && echo "root folder contents" || echo "$1 folder contents"
+	    total_folder_items=$(echo "${api_parsed_json_result}" | grep -E "^folder.childCount" | ${get_json_value})
+
+	    if [[ -z ${total_folder_items} ]]; then
+		echo "no items found"
+		return 1;
+	    else
+		for i in `seq 0 $((total_folder_items-1))`;
+		do
+	    	    item_name=$(echo "${api_parsed_json_result}" | grep -E "^children.${i}.name" | ${get_json_value})
+	    	    item_timestamp=$(echo "${api_parsed_json_result}" | grep -E "^children.${i}.lastModifiedDateTime" | ${get_json_value})
+	    	    if [[ -n $(echo "${api_parsed_json_result}" | grep -E "^children.${i}.folder") ]]; then
+	    		item_type='d'
+	    		item_size=$(echo "${api_parsed_json_result}" | grep -E "^children.${i}.folder.childCount" | ${get_json_value})
+	    	    elif [[ -n $(echo "${api_parsed_json_result}" | grep -E "^children.${i}.file") ]]; then
+	    		item_type=' '
+	    		item_size=$(echo "${api_parsed_json_result}" | grep -E "^children.${i}.size" | ${get_json_value})
+	    		let "total_files+=1"
+	    		let "total_file_size+=item_size"
+	    	    fi
+		    eval '$PRINTF "%s %s  %s\t%12d\t%b\n" "${item_timestamp%T*}" "${item_timestamp: -9:5}" "${item_type}" "${item_size}" "${item_name}"'
+		done
+	    fi
+	    echo -e "\ttotal number of items ${total_folder_items}"
+	    echo -e "\ttotal ${total_file_size} bytes in ${total_files} file(s)"
+	elif [[ -n $(echo "${api_parsed_json_result}" | grep -E "^file") ]]; then
+	    item_timestamp=$(echo "${api_parsed_json_result}" | grep -E "^lastModifiedDateTime" | ${get_json_value})
+	    item_size=$(echo "${api_parsed_json_result}" | grep -E "^size" | ${get_json_value})
+	    item_name=$(echo "${api_parsed_json_result}" | grep -E "^name" | ${get_json_value})
+	    item_url=$(echo "${api_parsed_json_result}" | grep -E "^@content.downloadUrl" | ${get_json_value})
+	    echo $PRINTF
+	    eval '$PRINTF "%s %s   \t%12d\t%b\t%s\n" "${item_timestamp%T*}" "${item_timestamp: -9:5}" "${item_size}" "${item_name}" "${item_url}"'
+	fi
 }
 
 # $@=path array
